### ISSUE TITLE
Backup/Restore Issues

### ISSUE THREAD

**Issue by BeeGrech** [freeotp/freeotp-android#410]
As documented in issues many times, If this critical feature doesn't work, the app is dead. Losing access to the app can mean catastrophic loss of login access. The restore/backup features need to be resolved before anyone should use this app. 
this is a critical failure and no release with full functionality for backup restore should be pushed.

**Comment by vdbhb59** [comment]
See if this works or helps you out:
https://github.com/freeotp/freeotp-android/issues/411#issuecomment-2322986024

**Comment by alexbakker** [comment]
I've written a bit about what's going on here in case you're interested: https://github.com/freeotp/freeotp-android/issues/283#issuecomment-2381379029. Various issues can occur depending on the version of Android, the version of FreeOTP and other factors.

**Comment by W48B1T** [comment]
I'll leave it here in case anybody stumbles across the backup/restore problems with FreeOTP: You can import the "externalBackup.xml" (the serialized java map containing json) in the Stratum Authenticator (https://github.com/stratumauth/app). From there on you can migrate / restore to where ever you like, since you can actually view your TOTP keys / URIs. I really don't get why problems like this don't get addressed by FreeOTP. It cost me multiple hours to find an implementation which can handle this "backup"-"xml".

**Comment by junaruga** [comment]
> I'll leave it here in case anybody stumbles across the backup/restore problems with FreeOTP: You can import the "externalBackup.xml" (the serialized java map containing json) in the Stratum Authenticator (https://github.com/stratumauth/app). From there on you can migrate / restore to where ever you like, since you can actually view your TOTP keys / URIs. I really don't get why problems like this don't get addressed. It cost me multiple hours to find an implementation which can handle this "backup"-"xml".

You saved me! I was able to migrate the data using Stratum Authenticator!

**Comment by mr-rubbish** [comment]
It does boggle the mind that the second most important feature of this app is broken. 😓
When I try porting the backup to another device and importing it, the other device recognises if I try to use a wrong password and only imports if the password is correct, but upon import... No keys are listed. If I import an old backup (from 2023) then all keys import fine.
I'm hoping this gets fixed and I will be keeping an eye out to test subsequent releases, but for the sake of my security I'll be switching to something that works!

**Comment by xprovate** [comment]
> I'll leave it here in case anybody stumbles across the backup/restore problems with FreeOTP: You can import the "externalBackup.xml" (the serialized java map containing json) in the Stratum Authenticator (https://github.com/stratumauth/app). From there on you can migrate / restore to where ever you like, since you can actually view your TOTP keys / URIs. I really don't get why problems like this don't get addressed. It cost me multiple hours to find an implementation which can handle this "backup"-"xml".

but why do I have to use a password when I import, the password is correct but it still can't be solved, what's the solution?

**Comment by steve-contrib** [comment]
You can solve the freeOTP import problem by importing your "externalBackup.xml" file from https://github.com/stratumauth/app

**Comment by Andsup** [comment]
same issue here.

Quite frustating for a security tools ....

Any one to look at the code source ?

thanks

**Comment by vdbhb59** [comment]
I just tried it today. Seems to work, but randomly the TOTP does not work. Odd.

**Comment by georgehank** [comment]
Just tried it *again*, and it again (not really surprising) didn't work.  FFS.

Both FreeOTPs are 2.0.6.
